name: Build the web book

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to generate docs from'
        type: choice
        options:
          - (same as workflow)
      release:
        description: Release this version
        type: boolean
        default: false
      update-latest:
        description: Overwrite latest (and root, if releasing)
        type: boolean
        default: true

permissions:
  contents: read

concurrency:
  group: hexdoc
  cancel-in-progress: false

defaults:
  run:
    working-directory: hexxybook

jobs:
  hexdoc:
    uses: object-Object/hexdoc/.github/workflows/hexdoc.yml@v0
    permissions: 
      contents: write
      pages: read
    with:
      python-version: "3.11"
      checkout: ${{ github.event_name == 'workflow_dispatch' && inputs.branch != '(same as workflow)' }}
      branch: ${{ inputs.branch }}
      publish-latest-and-root: |-
        ${{
          github.event_name != 'workflow_dispatch'
          || inputs.update-latest
        }}
      publish-release: ${{ github.event_name != 'workflow_dispatch' || inputs.release }}
